### PR TITLE
feat: support multiple alias and component pascal case

### PR DESCRIPTION
**Pull request by boydaihungst**
Support input multiple aliases [#8](https://github.com/CyCraft/vue-intellisense/issues/8#issue-777967906). Support component name pascal case like <BaseInput />

### CODE REVIEW

**Comment by mesqueeb** [comment]
@boydaihungst hey! thanks a lot for this PR!

The pascal case support is great and I would wanna merge immediately.

The alias support there is a slight issue:

The CLI file is supposed to not have any logic of its own, but just be a wrapper around the logic we have in `packages/scripts`. If you put the logic inside the CLI file itself, then people who want to use the script in a nodeJS deploy script won't be able to use it.

Could you try to refactor your PR so the logic resides in `packages/scripts` and the CLI just passes the correct args to the script? That would be really cool!

**Comment by boydaihungst** [comment]
done. :3 have a nice day

**Comment by boydaihungst** [comment]
Look like it has some bugs. Wait until I fixed it and add some unit tests then you can merge

**Comment by boydaihungst** [comment]
@mesqueeb Hey. I added some unit tests. Please review and merge this. I really need this tool for my custom vue3 [vue-enterprise-boilerplate](https://github.com/boydaihungst/vue-enterprise-boilerplate)

**Comment by mesqueeb** [comment]
I can probably merge and release on Monday

**Comment by mesqueeb** [comment]
@boydaihungst thanks again! released v0.3.0

let me know if you run into any issues!

**Pull request merged**
